#All the features should be declared here.

#feature_name:
#  controller_name:
#    - method_name1
#    - method_name2

user_feature:
  users_controller:
      - new
      - show
      - create

okta_feature:
  saml_controller:
      - init
      - consume
      - saml_settings
      - idp_metadata